# Dependabot configuration file for security updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit the number of open pull requests for npm dependencies
    open-pull-requests-limit: 5
    # Only security updates - not all version updates
    # This ensures we're notified of security issues without frequent
    # non-security updates for this demo project
    versioning-strategy: auto
    # Labels on pull requests
    labels:
      - "dependencies"
      - "security"
    # Allow updates for development dependencies
    allow:
      - dependency-type: "all"
    # Ignore certain dependencies (demo project)
    ignore:
      # Ignore major version updates for Clerk to avoid breaking changes
      - dependency-name: "@clerk/nextjs"
        update-types: ["version-update:semver-major"]
      - dependency-name: "clerk"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the `.github/workflows` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit the number of open pull requests
    open-pull-requests-limit: 5
    # Labels on pull requests
    labels:
      - "dependencies"
      - "security"
