# Dependabot configuration file for security updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the root directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    # Set a limit on pull requests
    open-pull-requests-limit: 5
    # Label pull requests
    labels:
      - "npm dependencies"
      - "security"
    # Only allow security updates for this demo project
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    # Don't allow automatic merging
    auto-merge: false

  # Also check for updates in the aws-demo directory
  - package-ecosystem: "npm"
    directory: "/aws-demo"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "npm dependencies"
      - "security"
    # Only allow security updates for this demo project
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    auto-merge: false

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "github-actions"
      - "ci"
    # Only allow security updates for this demo project
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    auto-merge: false
