repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
    -   id: gitleaks

# Comment out terraform hooks until tools are installed
# -   repo: https://github.com/antonbabenko/pre-commit-terraform
#     rev: v1.81.0
#     hooks:
#     -   id: terraform_fmt
#     -   id: terraform_tfsec
#     -   id: terraform_validate
#     -   id: terraform_docs

# Comment out ESLint hook until it's properly configured
# -   repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v8.38.0
#     hooks:
#     -   id: eslint
#         files: \.(js|ts|jsx|tsx)$
#         additional_dependencies:
#         -   eslint@8.38.0
#         -   eslint-config-next@13.4.0
#         -   typescript@5.0.4
